### ISSUE TITLE
Cannot use $ (jQuery) in worker thread

### ISSUE THREAD

**Issue by djechelon** [andywer/threadpool-js#11]
Hi, I just tried to integrate threadpool-js into my project for parallelizing AJAX requests to server.

I have made very little code adaptions but then I found that IE11 won't see the $ variable in its environment.

Visual Studio (the tool with wich I am debugging ASP.NET running on IE) shows my Javascript code as an anonymous block, which seems reasonable

Here is a fragment

    function anonymous(index) {

            aValue = $($(list).get(index)).val(); /Fails: $ is not defined, but list also

            var splitted = aValue.split('_');
            // nascondo cio che c'era prima
            $('#loader_' + aValue).show();
            $('#green_' + aValue).hide();
            $('#yellow_' + aValue).hide();
            $('#red_' + aValue).hide();
            $('#print_' + aValue).hide();
            $('#xls_' + aValue).hide();
            $('#summ_' + aValue).hide();

            $.ajax({
                type: 'GET',
                url: '/Check/Single',
                data: {

I think that a more general question can be: what about global variables in threadpool-js?

Thanks a lot. Sorry I can not contribute to your project with code, I am no JS developer

[Update]: same in Chrome

**Comment by andywer** [comment]
I just updated the readme in the develop branch. Have a look at https://github.com/andywer/threadpool-js/blob/develop/README.md#using-libraries-in-the-worker-code and remember that you cannot manipulate the DOM tree from within the parallel code.
