### ISSUE TITLE
webRTCissues

### ISSUE THREAD

**Issue by plusmaxz** [andywer/threadpool-js#12]
Uncaught ReferenceError: stream is not defined
    at main.js:24

**Comment by andywer** [comment]
Sorry @plusmaxz, but this is way too little information to tell anything about your issue. Doesn't even look related to this lib, since there is no `main.js` in `threadpool-js`.

Btw: `threadpool-js` has been deprecated: https://github.com/andywer/threadpool-js#threadpooljs---
