### ISSUE TITLE
importScripts.length

### ISSUE THREAD

**Issue by kander** [andywer/threadpool-js#6]
Hi And - I'm reviewing the code of the JS threadpool, and came across a statement in the source that has me puzzled. Not really an issue, more of a question. It's about line 21 in the genericWorkerCode, specifically:

if (importScripts && importScripts.length > 0) {
   importScripts.apply(null, scripts);
}

I can understand the check for importScript, but why the length check? It feels to me like you might have intended to check the length of "scripts" instead, to ensure that there's actually something to apply to the importScripts function?

Keep in mind that I'm not really a javascript superstar, just trying to demystify your ThreadPool for myself :)

**Comment by andywer** [comment]
No, you're completely right. Having this bug since the very first versions makes me think if anyone actually uses importScripts()...

The code's a little nasty, I know. It's really no beauty and I lack the time to refactor it. But it usually does its job :)

Thank you for the issue and keep on watching!

**Comment by andywer** [comment]
PS: Didn't mention it in the commit message... Fixed by https://github.com/andywer/threadpool-js/commit/1cd4c576a370169b12fb278008d8763a5fec842c

**Comment by kander** [comment]
Hi Andy! Perhaps having the readme.md make explicit mention of some of these functionalities would help? Loading a file instead of a function and importScripts don't seem to be covered by the documentation.

Glad to help out - the code isn't very polished, but it's definitely interesting to see how you built it.
