### ISSUE TITLE
Can no send multiple messages (i.e. streaming)

### ISSUE THREAD

**Issue by acterhd** [andywer/threadpool-js#8]
I try multiple calls of done, but get error with "triggerDone". Please fix it.

**Comment by andywer** [comment]
I have had a look at this and actually it is more a feature request. I would need to extend the library for streaming jobs support.

Currently the done() callback may only be called once to indicate that the job has finished, so the ThreadPool which does the scheduling knows that the job is done.

I will think about extending the library as soon as I have got time.

**Comment by andywer** [comment]
Hey there! I did not forget you. threadpool-js just did not provide a good foundation for this feature.

Have a look at [threads.js](https://github.com/andywer/threads.js) if you are still interested :)

Cheers
