### ISSUE TITLE
Error in bower.json

### ISSUE THREAD

**Issue by miltonhultgren** [andywer/threadpool-js#9]
The main attribute should point to dist/threadpool.js else automatic dependency injectors won't link it correctly.

**Comment by andywer** [comment]
Ahh, thanks for the heads-up. Which dependency injection tool are you using?

**Comment by miltonhultgren** [comment]
We're using Grunt with wiredep.

**Comment by andywer** [comment]
Have a look at the develop branch, please. Having the bower.json point to the dist script and the package.json point to the source script should work fine.

**Comment by miltonhultgren** [comment]
Yeah that should do it, I did the same change on my local copy (leaving the package.json as it was) and it all works fine so that's all that's needed.

**Comment by miltonhultgren** [comment]
I saw that you merged the fix into your master branch but could you also make a release (tag I guess) so that the fix appears in a version that bower can pull?

**Comment by andywer** [comment]
Done. You may use version 0.4.1.

Thanks for the hint!

**Comment by miltonhultgren** [comment]
Works great! Thanks for the quick fix!
